version: "3.7"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    user: mongodb

  web:
    build: .
    container_name: nodegoat
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo:27017/nodegoat
    command: sh -c "apt update && apt install -y netcat && until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"
    depends_on:
      - mongo
    ports:
      - "4000:4000"
